import { defineConfig } from "tsup"

export default defineConfig({
  entry: [
    "src/index.ts",
    "src/index.browser.ts",
    "src/collections.ts",
    "src/itertools.ts",
    "src/functools.ts",
    "src/math.ts",
    "src/random.ts",
    "src/datetime.ts",
    "src/re.ts",
    "src/json.ts",
    "src/os.browser.ts",
    "src/os.node.ts",
    "src/string.ts",
    "src/sys.ts",
    "src/time.ts",
    "src/copy.ts",
    "src/base64.ts",
    "src/uuid.ts",
    "src/hashlib.ts",
    "src/pathlib.browser.ts",
    "src/pathlib.node.ts",
    "src/glob.browser.ts",
    "src/glob.node.ts",
    "src/shutil.browser.ts",
    "src/shutil.node.ts",
    "src/tempfile.browser.ts",
    "src/tempfile.node.ts",
    "src/subprocess.ts",
    "src/urllib.ts",
    "src/logging.browser.ts",
    "src/logging.node.ts"
  ],
  format: ["esm"],
  dts: true,
  clean: true
})
